<br>
<div id="main-home-content" class="home-content home-page container" role="main">
    <div id="pl-12" class="panel-layout">
        <div id="pg-12-4" class="panel-grid panel-no-style">
            <div id="pgc-12-4-0" class="panel-grid-cell">
                <div id="panel-12-4-0-0" class="so-panel widget widget_heading panel-first-child"
                     data-index="9">
                    <div class="thim-widget-heading thim-widget-heading-base">
                        <div class="sc_heading text-left"><h3 class="title">Administración de los cursos</h3>
                            <p class="sub-heading" style="">Panel para administrar los cursos.</p><span class="line"></span></div>
                    </div>
                </div>
                <div id="panel-12-4-0-1" class="so-panel widget widget_list-event panel-last-child"
                     data-index="10">
                    <div class="thim-widget-list-event thim-widget-list-event-base">
                        <div class="thim-list-event">
                            <a id="crearCursoButton" class="view-all" href="#">Crear curso</a>
                            <?php foreach ($course as $key): ?>
                            <div class="item-event post-3062 tp_event type-tp_event status-tp-event-upcoming has-post-thumbnail hentry pmpro-has-access">
                                <div class="image"><img
                                        src="<?=$this->url->get('front/courses_images/'.$key->getMainImage())?>"
                                        alt="course-6" title="course-6" width="450" height="233"></div>
                                <div class="event-wrapper">
                                    <h5 class="title"><a href="">
                                            <?=$key->getName()?></a></h5>
                                    <div class="meta">
                                        <div class="time"><i class="fa fa-eye"></i> <a href="/instructor/crear-curso/temario/<?=$key->getCouid()?>">Ver temario</a>
                                        </div>
                                        <div class="time"><i class="fa fa-pencil"></i> <a href="/instructor/crear-curso/editar-curso/<?=$key->getCouid()?>">Editar</a>
                                        </div>
                                        <div class="time"><i class="fa fa-envelope"></i> <a onclick="sendCourse('<?=$key->getCouid()?>','<?=$key->getStatus()?>')" href="#">Enviar a revision</a>
                                        </div>
                                        <div class="location"><i class="fa fa-times"></i><a>Eliminar</a>
                                        </div>
                                        <div class="location" id="statusCourse">
                                            <?php if($key->getStatus()=='INACTIVE'){
                                             ?>Estado: Inactivo <?php
                                            }elseif ($key->getStatus()=='ACTIVE'){
                                             ?> Estado: Activo <?php
                                            }elseif ($key->getStatus()=='SEND'){
                                                ?> Estado:Enviado <?php
                                            } ?>

                                        </div>
                                    </div>

                                    <div class="description">
                                            <?=$key->getDescription()?>
                                        </div>
                                </div>
                           </div>
                           <?php endforeach; ?>
                        </div>
                     </div>
                 </div>
            </div>
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>

