<br>
<div id="main-home-content" class="home-content home-page container" role="main">
    <div id="pl-12" class="panel-layout">
        <div id="pg-12-4" class="panel-grid panel-no-style">
            <div id="pgc-12-4-0" class="panel-grid-cell">
                <div id="panel-12-4-0-0" class="so-panel widget widget_heading panel-first-child"
                     data-index="9">
                    <div class="thim-widget-heading thim-widget-heading-base">
                        <div class="sc_heading text-left"><h3 class="title">Editar curso</h3>
                        </div>
                    </div>
                </div>
                <div class="container">
                    <form id="newCourse">
                    <div class="row" style="text-align: center">
                        <input type="hidden" name="couid" value="<?=$courseid?>">
                        <label class="col-md-3">Titulo:</label>
                        <div class="col-md-3">
                            <input type="text" name="courseTitle" value="<?=$course->getName()?>" class="form-control cPCourse" placeholder="Titulo" style="text-align: center">
                        </div>
                        <label class="col-md-3">Permalink:</label>
                        <div class="col-md-3">
                            <input type="text" value="<?=$course->getPermalink()?>" name="coursePermalink" id="coursePermalink" class="form-control" placeholder="Permalink" style="text-align: center" readonly>
                        </div>
                    </div>
                    <br>
                    <div class="row" style="text-align: center">
                        <h2 class="col-md-3">Resumen:</h2>
                        <div class="col-md-9">
                         <textarea class="form-control ckeditor" name="sumary" ><?=$course->getSummary()?></textarea>
                            <textarea style="display: none" name="sumary2" id="sumary2"></textarea>
                        </div>
                    </div>
                        <br>
                        <div class="row" style="text-align: center">
                            <h2 class="col-md-3">Video de introducción:</h2>
                            <div class="col-md-9">
                                <div id="courseVideo" class="dropzone">
                                    <div class="dz-default dz-message">
                                        <h2 style="text-align:center;position: relative;top:-30px;" id="content-video">
                                            <i class="fa fa-cloud-upload" style="font-size: 88px;"></i><br>
                                            Arrastra un vídeo<br><i style="font-size: 14px">o haz click para seleccionar manualmente</i>
                                        </h2>
                                        <input type="hidden" value="<?=$course->getIntroductionVideo()?>" name="video_introduction" id="video_introduction">
                                    </div>

                                </div>
                            </div>
                        </div>

                        <br>
                        <div class="row" style="text-align: center">
                            <h2 class="col-md-3">Descripción:</h2>
                            <div class="col-md-9">
                                <textarea class="form-control ckeditor" name="description" ><?=$course->getDescription()?></textarea>
                                <textarea style="display: none" name="description2" id="description2"></textarea>
                            </div>
                        </div>

                        <br>
                    <div class="row" style="text-align: center">
                        <h2 class="col-md-3">Imagen:</h2>
                          <div class="col-md-9">
                                <div id="courseImage" class="dropzone">
                                    <div class="dz-default dz-message">
                                        <h2 style="text-align:center;position: relative;top:-30px;" id="content-image">
                                            <i class="fa fa-cloud-upload" style="font-size: 88px;"></i><br>
                                            Arrastra una imagen<br><i style="font-size: 14px">o haz click para seleccionar manualmente</i>
                                        </h2>
                                        <input type="hidden" value="<?=$course->getMainImage()?>" name="image-2" id="image-2">
                                    </div>

                                </div>
                            </div>
                    </div>
                    <br>
                    <div class="row" style="text-align: center">
                        <label class="col-md-3">¿Que se aprendera?:</label>
                        <div class="col-md-3">
                           <span>En esta parte se pondra todo lo que la persona aprendera:</span>
                           <input id="aprendizaje_curso" type="text" class="form-control" style="text-align: center"><a id="agregar_aprendizaje" class="fa fa-arrow-circle-o-right"></a>
                        </div>
                        <div class="col-md-6" id="learning">
                            <?php foreach ($learning as $key): ?>
                            <div id="learning_add_<?=$key->getLearid()?>">
                                <li><?=$key->getName()?> <a class="fa fa-times" onclick="deletesLearnRequire(<?=$key->getLearid()?>,'learning_add')"></a></li>
                                <input type="hidden" value='<?=$key->getName()?>' name="aprendizaje[]">
                            </div>
                            <?php endforeach; ?>
                        </div>
                    </div>

                    <br>
                    <div class="row" style="text-align: center">
                        <label class="col-md-3">Requisitos:</label>
                        <div class="col-md-3">
                            <span>En esta parte se pondran los requisitos del curso:</span>
                            <input id="requisitos_curso" type="text" class="form-control" style="text-align: center"><a id="agregar_requisito" class="fa fa-arrow-circle-o-right"></a>
                        </div>
                        <div class="col-md-6" id="requirements">
                           <?php foreach ($requeriments as $cnv): ?>
                            <div id="requeriment_add_<?=$cnv->getReqid()?>">
                                <li><?=$cnv->getRequeriments()?> <a class="fa fa-times" onclick="deletesLearnRequire(<?=$cnv->getReqid()?>,'requeriment_add')"></a></li>
                                <input type="hidden" value='<?=$cnv->getRequeriments()?>' name="requerimiento[]">
                            </div>
                            <?php endforeach; ?>
                        </div>
                    </div>


                        <br>
                    <div class="row" style="text-align: center">
                        <label class="col-md-3">Duración:</label>
                        <div class="col-md-3">
                            <input type="text" value="<?=$course->getDuration()?>" name="duration" id="duration" class="form-control" style="text-align: center">
                        </div>
                        <label class="col-md-3">Precio:</label>
                        <div class="col-md-3">
                            <input type="text" value="<?=$course->getPrice()?>" name="price" class="form-control" style="text-align: center">
                        </div>
                    </div>
                    <br>
                    <div class="row" style="text-align: center">
                        <label class="col-md-3">Categoria:</label>
                        <div class="col-md-3">
                            <select id="selectCategory" class="form-control" name="category" >
                                <option value="">Seleccionar categoria</option>
                                <?php if(count($course->getSubid())>0){
                                    $consultaSubcategory=\Modules\Models\CdSubcategory::findFirst("subid=".$course->getSubid());
                                 ?>
                                <?php foreach ($category as $key):?>
                                <option <?=$consultaSubcategory->getCatid()==$key->getCatid()?'selected':''?> value="<?=$key->getCatid()?>"><?=$key->getName()?></option>
                                <?php endforeach;   }else{?>
                                    <?php foreach ($category as $key): ?>
                                      <option value="<?=$key->getCatid()?>"><?=$key->getName()?></option>
                                    <?php
                                endforeach; }?>
                            </select>
                        </div>
                        <label class="col-md-3">Subcategoria:</label>
                        <div class="col-md-3">
                          <select class="form-control" id="select_subcategory" name="subid">
                              <option value="">Seleccionar subcategoria</option>
                              <?php foreach ($subcategory as $key): ?>
                              <option <?=$course->getSubid()==$key->getSubid()?"selected":""?> value="<?=$key->getSubid()?>"><?=$key->getName()?></option>
                              <?php endforeach; ?>
                          </select>
                        </div>
                    </div>
                        <br>
                        <div class="row" style="text-align: center">
                            <div class="col-md-3"></div>
                            <label class="col-md-3">Lenguage:</label>
                            <div class="col-md-3">
                             <?php $lenguage=array("Español","Ingles","Portugues","Frances") ?>
                                <select class="form-control"name="lenguage">
                                    <option value="">Seleccione un lenguaje</option>
                                    <?php foreach ($lenguage as $len): ?>
                                    <option <?=$course->getLenguage()==$len?'selected':''?> value="<?=$len?>"><?=$len?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>

                        <br>
                    <div class="row" style="text-align: center">
                        <div class="col-md-12">
                             <input type="submit" value="Guardar" class="wpcf7-form-control wpcf7-submit">
                        </div>
                    </div>
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>


