<div id="main-home-content" class="home-content home-page container" role="main">
    <div id="pl-12" class="panel-layout">
        <div id="pg-12-1" class="panel-grid panel-has-style">
            <div class="thim-best-industry panel-row-style panel-row-style-for-12-1">
                <div id="pgc-12-1-0" class="panel-grid-cell">
                    <div id="panel-12-1-0-0"
                         class="so-panel widget widget_icon-box panel-first-child panel-last-child"
                         data-index="1">
                        <div class="thim-widget-icon-box thim-widget-icon-box-base">
                            <div class="wrapper-box-icon has_custom_image has_read_more text-left overlay "
                                 data-text-readmore="#ffb606">
                                <div class="smicon-box iconbox-left">
                                    <div class="boxes-icon" style="width: 135px;height: 135px;"><span
                                            class="inner-icon"><span class="icon icon-images"><img
                                                    src="https://3ek5k1tux0822q3g83e30fye-wpengine.netdna-ssl.com/wp-content/uploads/2015/10/logo-top-1.png"
                                                    alt="logo-top-1" title="logo-top-1" width="61"
                                                    height="52"></span></span></div>
                                    <div class="content-inner" style="width: calc( 100% - 135px - 15px);">
                                        <div class="sc-heading article_heading"><h3
                                                class="heading__primary">Mejor industria del aprendisaje</h3></div>
                                        <a class="smicon-read sc-btn" target="_self" href="#"
                                           style="color: #ffb606;">View More<i
                                                class="fa fa-chevron-right"></i></a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="pgc-12-1-1" class="panel-grid-cell">
                    <div id="panel-12-1-1-0"
                         class="so-panel widget widget_icon-box panel-first-child panel-last-child"
                         data-index="2">
                        <div class="thim-widget-icon-box thim-widget-icon-box-base">
                            <div class="wrapper-box-icon has_custom_image has_read_more text-left overlay "
                                 data-text-readmore="#ffb606">
                                <div class="smicon-box iconbox-left">
                                    <div class="boxes-icon" style="width: 132px;height: 132px;"><span
                                            class="inner-icon"><span class="icon icon-images"><img
                                                    src="https://3ek5k1tux0822q3g83e30fye-wpengine.netdna-ssl.com/wp-content/uploads/2015/10/logo-top-2.png"
                                                    alt="logo-top-2" title="logo-top-2" width="66"
                                                    height="51"></span></span></div>
                                    <div class="content-inner" style="width: calc( 100% - 132px - 15px);">
                                        <div class="sc-heading article_heading"><h3
                                                class="heading__primary">Aprende cursos en linea</h3></div>
                                        <a class="smicon-read sc-btn" target="_self" href="#"
                                           style="color: #ffb606;">View More<i
                                                class="fa fa-chevron-right"></i></a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="pgc-12-1-2" class="panel-grid-cell">
                    <div id="panel-12-1-2-0"
                         class="so-panel widget widget_icon-box panel-first-child panel-last-child"
                         data-index="3">
                        <div class="thim-widget-icon-box thim-widget-icon-box-base">
                            <div class="wrapper-box-icon has_custom_image has_read_more text-left overlay "
                                 data-text-readmore="#ffb606">
                                <div class="smicon-box iconbox-left">
                                    <div class="boxes-icon" style="width: 135px;height: 135px;"><span
                                            class="inner-icon"><span class="icon icon-images"><img
                                                    src="https://3ek5k1tux0822q3g83e30fye-wpengine.netdna-ssl.com/wp-content/uploads/2015/10/logo-top-3.png"
                                                    alt="logo-top-3" title="logo-top-3" width="59"
                                                    height="50"></span></span></div>
                                    <div class="content-inner" style="width: calc( 100% - 135px - 15px);">
                                        <div class="sc-heading article_heading"><h3
                                                class="heading__primary">Biblioteca &#38; Tienda</h3></div>
                                        <a class="smicon-read sc-btn" target="_self" href="#"
                                           style="color: #ffb606;">View More<i
                                                class="fa fa-chevron-right"></i></a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="pg-12-2" class="panel-grid panel-no-style">
            <div id="pgc-12-2-0" class="panel-grid-cell">
                <div id="panel-12-2-0-0" class="so-panel widget widget_heading panel-first-child"
                     data-index="4">
                    <div class="thim-widget-heading thim-widget-heading-base">
                        <div class="sc_heading text-left"><h3 class="title">Cursos populares</h3><span
                                class="line"></span></div>
                    </div>
                </div>
                <div id="panel-12-2-0-1" class="so-panel widget widget_courses panel-last-child"
                     data-index="5">
                    <div class="thim-widget-courses thim-widget-courses-base">
                        <div class="thim-carousel-wrapper thim-course-carousel thim-course-grid"
                             data-visible="4" data-pagination="0" data-navigation="1" data-autoplay="0">
                          <?php foreach ($cursos as $key):?>
                            <div class="course-item">
                                <div class="course-thumbnail"><a class="thumb"
                                                                 href="/instructor/cursos/<?=$key->getPermalink()?>"><img
                                            src="/front/courses_images/<?=$key->getMainImage()?>"
                                            alt="Introduction LearnPress &#8211; LMS plugin" title="course-4"
                                            width="450" height="450" style="height: 270px;width: 270px"></a><a class="course-readmore"
                                                                            href="/instructor/cursos/<?=$key->getPermalink()?>">Leer más</a></div>
                                <div class="thim-course-content">
                                    <?php $client = \Modules\Models\CdClient::findFirst('clieid='.$key->getClieid()); ?>
                                    <div class="course-author" itemscope
                                         itemtype="http://schema.org/Person"><img alt="Admin bar avatar"
                                                                                  src="<?=$client->getImg()==''?'/front/img/user-img.png':'/front/coursesimage/'.$client->getImg()?>"
                                                                                  class="avatar avatar-40 photo"
                                                                                  height="40" width="40"/>
                                        <div class="author-contain"><label
                                                itemprop="jobTitle">Teacher</label>
                                            <div class="value" itemprop="name"><a
                                                    href="#">
                                                    <?=$client->getNames()?> <?=$client->getLastName()?></a></div>
                                        </div>
                                    </div>
                                    <h2 class="course-title"><a
                                            href="instructor/cursos/<?=$key->getPermalink()?>">
                                            <?=$key->getName()?></a></h2>
                                    <div class="course-meta">
                                        <div class="course-students"><label>Students</label>
                                            <div class="value"><i class="fa fa-group"></i> 570</div>
                                        </div>
                                        <div class="course-comments-count">
                                            <div class="value"><i class="fa fa-comment"></i>3</div>
                                        </div>
                                        <div class="course-price" itemprop="offers" itemscope
                                             itemtype="http://schema.org/Offer">
                                            <div class="value" itemprop="price"> $<?=$key->getPrice()?>.00</div>
                                            <meta itemprop="priceCurrency" content="&#36;"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                          <?php endforeach; ?>
                            <div class="course-item">
                                <div class="course-thumbnail"><a class="thumb"
                                                                 href="https://educationwp.thimpress.com/courses/node/"><img
                                            src="https://3ek5k1tux0822q3g83e30fye-wpengine.netdna-ssl.com/wp-content/uploads/2015/06/course-1-450x450.jpg"
                                            alt="From Zero to Hero with Nodejs" title="course-1" width="450"
                                            height="450"></a><a class="course-readmore"
                                                                href="https://educationwp.thimpress.com/courses/node/">Read
                                        More</a></div>
                                <div class="thim-course-content">
                                    <div class="course-author" itemscope
                                         itemtype="http://schema.org/Person"><img alt="Admin bar avatar"
                                                                                  src="https://3ek5k1tux0822q3g83e30fye-wpengine.netdna-ssl.com/wp-content/uploads/learn-press-profile/7/9c081444f942cc8fe0ddf55631b584e2.jpg"
                                                                                  class="avatar avatar-40 photo"
                                                                                  height="40" width="40"/>
                                        <div class="author-contain"><label
                                                itemprop="jobTitle">Teacher</label>
                                            <div class="value" itemprop="name"><a
                                                    href="https://educationwp.thimpress.com/profile/keny/courses/">
                                                    Keny White </a></div>
                                        </div>
                                    </div>
                                    <h2 class="course-title"><a
                                            href="https://educationwp.thimpress.com/courses/node/"> From
                                            Zero to Hero with Nodejs</a></h2>
                                    <div class="course-meta">
                                        <div class="course-students"><label>Students</label>
                                            <div class="value"><i class="fa fa-group"></i> 165</div>
                                        </div>
                                        <div class="course-comments-count">
                                            <div class="value"><i class="fa fa-comment"></i>1</div>
                                        </div>
                                        <div class="course-price" itemprop="offers" itemscope
                                             itemtype="http://schema.org/Offer">
                                            <div class="value free-course" itemprop="price"> Free</div>
                                            <meta itemprop="priceCurrency" content="&#36;"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="course-item">
                                <div class="course-thumbnail"><a class="thumb"
                                                                 href="https://educationwp.thimpress.com/courses/python/"><img
                                            src="https://3ek5k1tux0822q3g83e30fye-wpengine.netdna-ssl.com/wp-content/uploads/2015/12/course-16-450x450.jpg"
                                            alt="Learn Python &#8211; Interactive Python" title="course-16"
                                            width="450" height="450"></a><a class="course-readmore"
                                                                            href="https://educationwp.thimpress.com/courses/python/">Read
                                        More</a></div>
                                <div class="thim-course-content">
                                    <div class="course-author" itemscope
                                         itemtype="http://schema.org/Person"><img alt="Admin bar avatar"
                                                                                  src="https://3ek5k1tux0822q3g83e30fye-wpengine.netdna-ssl.com/wp-content/uploads/learn-press-profile/1/21232f297a57a5a743894a0e4a801fc3.jpg"
                                                                                  class="avatar avatar-40 photo"
                                                                                  height="40" width="40"/>
                                        <div class="author-contain"><label
                                                itemprop="jobTitle">Teacher</label>
                                            <div class="value" itemprop="name"><a
                                                    href="https://educationwp.thimpress.com/profile/admin/courses/">
                                                    Hinata Hyuga </a></div>
                                        </div>
                                    </div>
                                    <h2 class="course-title"><a
                                            href="https://educationwp.thimpress.com/courses/python/"> Learn
                                            Python &#8211; Interactive Python</a></h2>
                                    <div class="course-meta">
                                        <div class="course-students"><label>Students</label>
                                            <div class="value"><i class="fa fa-group"></i> 50</div>
                                        </div>
                                        <div class="course-comments-count">
                                            <div class="value"><i class="fa fa-comment"></i>1</div>
                                        </div>
                                        <div class="course-price" itemprop="offers" itemscope
                                             itemtype="http://schema.org/Offer">
                                            <div class="value" itemprop="price"> &#36;69.00</div>
                                            <meta itemprop="priceCurrency" content="&#36;"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="course-item">
                                <div class="course-thumbnail"><a class="thumb"
                                                                 href="https://educationwp.thimpress.com/courses/your-complete-guide-to-photography/"><img
                                            src="https://3ek5k1tux0822q3g83e30fye-wpengine.netdna-ssl.com/wp-content/uploads/2015/11/course-9-450x450.jpg"
                                            alt="Your Complete Guide to Photography" title="course-9"
                                            width="450" height="450"></a><a class="course-readmore"
                                                                            href="https://educationwp.thimpress.com/courses/your-complete-guide-to-photography/">Read
                                        More</a></div>
                                <div class="thim-course-content">
                                    <div class="course-author" itemscope
                                         itemtype="http://schema.org/Person"><img alt="Admin bar avatar"
                                                                                  src="https://3ek5k1tux0822q3g83e30fye-wpengine.netdna-ssl.com/wp-content/uploads/learn-press-profile/1/21232f297a57a5a743894a0e4a801fc3.jpg"
                                                                                  class="avatar avatar-40 photo"
                                                                                  height="40" width="40"/>
                                        <div class="author-contain"><label
                                                itemprop="jobTitle">Teacher</label>
                                            <div class="value" itemprop="name"><a
                                                    href="https://educationwp.thimpress.com/profile/admin/courses/">
                                                    Hinata Hyuga </a></div>
                                        </div>
                                    </div>
                                    <h2 class="course-title"><a
                                            href="https://educationwp.thimpress.com/courses/your-complete-guide-to-photography/">
                                            Your Complete Guide to Photography</a></h2>
                                    <div class="course-meta">
                                        <div class="course-students"><label>Students</label>
                                            <div class="value"><i class="fa fa-group"></i> 45</div>
                                        </div>
                                        <div class="course-comments-count">
                                            <div class="value"><i class="fa fa-comment"></i>1</div>
                                        </div>
                                        <div class="course-price" itemprop="offers" itemscope
                                             itemtype="http://schema.org/Offer">
                                            <div class="value has-origin" itemprop="price"><span
                                                    class="course-origin-price">&#36;60.00</span> &#36;39.00
                                            </div>
                                            <meta itemprop="priceCurrency" content="&#36;"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="course-item">
                                <div class="course-thumbnail"><a class="thumb"
                                                                 href="https://educationwp.thimpress.com/courses/learning-jquery-mobile-for-beginners/"><img
                                            src="https://3ek5k1tux0822q3g83e30fye-wpengine.netdna-ssl.com/wp-content/uploads/2015/06/course-5-450x450.jpg"
                                            alt="Learning jQuery Mobile for Beginners" title="course-5"
                                            width="450" height="450"></a><a class="course-readmore"
                                                                            href="https://educationwp.thimpress.com/courses/learning-jquery-mobile-for-beginners/">Read
                                        More</a></div>
                                <div class="thim-course-content">
                                    <div class="course-author" itemscope
                                         itemtype="http://schema.org/Person"><img alt="Admin bar avatar"
                                                                                  src="https://3ek5k1tux0822q3g83e30fye-wpengine.netdna-ssl.com/wp-content/uploads/learn-press-profile/1/21232f297a57a5a743894a0e4a801fc3.jpg"
                                                                                  class="avatar avatar-40 photo"
                                                                                  height="40" width="40"/>
                                        <div class="author-contain"><label
                                                itemprop="jobTitle">Teacher</label>
                                            <div class="value" itemprop="name"><a
                                                    href="https://educationwp.thimpress.com/profile/admin/courses/">
                                                    Hinata Hyuga </a></div>
                                        </div>
                                    </div>
                                    <h2 class="course-title"><a
                                            href="https://educationwp.thimpress.com/courses/learning-jquery-mobile-for-beginners/">
                                            Learning jQuery Mobile for Beginners</a></h2>
                                    <div class="course-meta">
                                        <div class="course-students"><label>Students</label>
                                            <div class="value"><i class="fa fa-group"></i> 32</div>
                                        </div>
                                        <div class="course-comments-count">
                                            <div class="value"><i class="fa fa-comment"></i>1</div>
                                        </div>
                                        <div class="course-price" itemprop="offers" itemscope
                                             itemtype="http://schema.org/Offer">
                                            <div class="value" itemprop="price"> &#36;30.00</div>
                                            <meta itemprop="priceCurrency" content="&#36;"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="course-item">
                                <div class="course-thumbnail"><a class="thumb"
                                                                 href="https://educationwp.thimpress.com/courses/become-a-php-master-and-make-money-fast/"><img
                                            src="https://3ek5k1tux0822q3g83e30fye-wpengine.netdna-ssl.com/wp-content/uploads/2015/06/course-2-450x450.jpg"
                                            alt="Become a PHP Master and Make Money" title="course-2"
                                            width="450" height="450"></a><a class="course-readmore"
                                                                            href="https://educationwp.thimpress.com/courses/become-a-php-master-and-make-money-fast/">Read
                                        More</a></div>
                                <div class="thim-course-content">
                                    <div class="course-author" itemscope
                                         itemtype="http://schema.org/Person"><img alt="Admin bar avatar"
                                                                                  src="https://3ek5k1tux0822q3g83e30fye-wpengine.netdna-ssl.com/wp-content/uploads/learn-press-profile/7/9c081444f942cc8fe0ddf55631b584e2.jpg"
                                                                                  class="avatar avatar-40 photo"
                                                                                  height="40" width="40"/>
                                        <div class="author-contain"><label
                                                itemprop="jobTitle">Teacher</label>
                                            <div class="value" itemprop="name"><a
                                                    href="https://educationwp.thimpress.com/profile/keny/courses/">
                                                    Keny White </a></div>
                                        </div>
                                    </div>
                                    <h2 class="course-title"><a
                                            href="https://educationwp.thimpress.com/courses/become-a-php-master-and-make-money-fast/">
                                            Become a PHP Master and Make Money</a></h2>
                                    <div class="course-meta">
                                        <div class="course-students"><label>Students</label>
                                            <div class="value"><i class="fa fa-group"></i> 28</div>
                                        </div>
                                        <div class="course-comments-count">
                                            <div class="value"><i class="fa fa-comment"></i>1</div>
                                        </div>
                                        <div class="course-price" itemprop="offers" itemscope
                                             itemtype="http://schema.org/Offer">
                                            <div class="value has-origin" itemprop="price"><span
                                                    class="course-origin-price">&#36;80.00</span> &#36;69.00
                                            </div>
                                            <meta itemprop="priceCurrency" content="&#36;"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="pg-12-4" class="panel-grid panel-no-style">
            <div id="pgc-12-4-0" class="panel-grid-cell">
                <div id="panel-12-4-0-0" class="so-panel widget widget_heading panel-first-child"
                     data-index="9">
                    <div class="thim-widget-heading thim-widget-heading-base">
                        <div class="sc_heading text-left"><h3 class="title">Eventos</h3>
                            <p class="sub-heading" style="">Proximos eventos para alimentar tu cerebro</p><span class="line"></span></div>
                    </div>
                </div>
                <div id="panel-12-4-0-1" class="so-panel widget widget_list-event panel-last-child"
                     data-index="10">
                    <div class="thim-widget-list-event thim-widget-list-event-base">
                        <div class="thim-list-event"><a class="view-all"
                                                        href="https://educationwp.thimpress.com/events/">View
                                All</a>
                            <div class="item-event post-3062 tp_event type-tp_event status-tp-event-upcoming has-post-thumbnail hentry pmpro-has-access">
                                <div class="time-from">
                                    <div class="date"> 30</div>
                                    <div class="month"> May</div>
                                </div>
                                <div class="image"><img
                                        src="https://3ek5k1tux0822q3g83e30fye-wpengine.netdna-ssl.com/wp-content/uploads/2015/06/course-6-450x233.jpg"
                                        alt="course-6" title="course-6" width="450" height="233"></div>
                                <div class="event-wrapper"><h5 class="title"><a
                                            href="https://educationwp.thimpress.com/events/eduma-autumn-2015/">
                                            Eduma Autumn 2017</a></h5>
                                    <div class="meta">
                                        <div class="time"><i class="fa fa-clock-o"></i> 8:00 am - 5:00 pm
                                        </div>
                                        <div class="location"><i class="fa fa-map-marker"></i> Venice, Italy
                                        </div>
                                    </div>
                                    <div class="description"><p>Morbi accumsan ipsum velit. Nam nec tellus a
                                            odio tincidunt auctor a ornare odio. Sed non mauris itae erat
                                            conuat</p></div>
                                </div>
                            </div>
                            <div class="item-event post-2952 tp_event type-tp_event status-tp-event-upcoming has-post-thumbnail hentry pmpro-has-access">
                                <div class="time-from">
                                    <div class="date"> 18</div>
                                    <div class="month"> December</div>
                                </div>
                                <div class="image"><img
                                        src="https://3ek5k1tux0822q3g83e30fye-wpengine.netdna-ssl.com/wp-content/uploads/2015/11/event-2-450x233.jpg"
                                        alt="event-2" title="event-2" width="450" height="233"></div>
                                <div class="event-wrapper"><h5 class="title"><a
                                            href="https://educationwp.thimpress.com/events/elegant-light-box-paper-cut-dioramas-1/">
                                            Elegant Light Box Paper Cut Dioramas</a></h5>
                                    <div class="meta">
                                        <div class="time"><i class="fa fa-clock-o"></i> 8:00 am - 5:00 pm
                                        </div>
                                        <div class="location"><i class="fa fa-map-marker"></i> Vancouver,
                                            Canada
                                        </div>
                                    </div>
                                    <div class="description"><p>Morbi accumsan ipsum velit. Nam nec tellus a
                                            odio tincidunt auctor a ornare odio. Sed non mauris itae erat
                                            conuat</p></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="pg-12-5" class="panel-grid panel-has-style">
        </div>
        <div id="pg-12-6" class="panel-grid panel-no-style">

        </div>
        <div id="pg-12-7" class="panel-grid panel-no-style">

        </div>
    </div>
</div>
