<html>
   <head>
       <title>Visalizador de videos</title>
       <link rel="stylesheet" href="<?=$this->url->get('front/css/bootstrap.css')?>">
       <link rel="stylesheet" href="<?=$this->url->get('front/css/videos.css')?>">
       <link rel="stylesheet" href="<?=$this->url->get('front/css/video-js.css')?>">
       <script src="<?=$this->url->get('front/js/videojs-ie8.min.js')?>"></script>
   </head>
<body>
   <video id="my-video" class="video-js" controls preload="auto" style="width: 100%;height: 100%"
          poster="MY_VIDEO_POSTER.jpg" data-setup="{}">
       <source src="/media/videos/<?=$videos->getVideo()?>" type="video/mp4">
   </video>
   <script src="<?=$this->url->get('front/js/video.js')?>"></script>
</body>
</html>


<?php exit();?>